
import { EpisodeData } from './types';

export const PODCAST_DATA: EpisodeData[] = [
  { id: 'E01', title: '走进真实世界', type: 'Guest', playCount: 53.3, commentCount: 879 },
  { id: 'E02', title: '市场无法预测', type: 'Guest', playCount: 12.4, commentCount: 282 },
  { id: 'E03', title: '投资和网球', type: 'Guest', playCount: 8.5, commentCount: 398 },
  { id: 'E04', title: '别折磨自己', type: 'Guest', playCount: 12.2, commentCount: 739 },
  { id: 'E05', title: '别人的战争', type: 'Guest', playCount: 13.3, commentCount: 683 },
  { id: 'E06', title: '共同创造', type: 'Guest', playCount: 7.5, commentCount: 232 },
  { id: 'E07', title: '别着急燃烧自己', type: 'Guest', playCount: 9.5, commentCount: 335 },
  { id: 'E08', title: '不明真相', type: 'Guest', playCount: 8.4, commentCount: 280 },
  { id: 'E09', title: '让爱你的人更爱你', type: 'Guest', playCount: 11.9, commentCount: 512 },
  { id: 'E10', title: '让万物穿过自己', type: 'Solo', playCount: 195.5, commentCount: 6040 },
  { id: 'E11', title: '投资成功的开始', type: 'Guest', playCount: 6.5, commentCount: 365 },
  { id: 'E12', title: '人生最有价值的时刻', type: 'Guest', playCount: 15.0, commentCount: 431 },
  { id: 'E13', title: '最好的投资', type: 'Guest', playCount: 17.9, commentCount: 648 },
  { id: 'E14', title: '自己的故事', type: 'Guest', playCount: 6.9, commentCount: 261 },
  { id: 'E15', title: '张无忌的无限游戏', type: 'Solo', playCount: 11.1, commentCount: 693 },
  { id: 'E16', title: '少楠：彼此成长', type: 'Guest', playCount: 11.7, commentCount: 711 },
  { id: 'E17', title: '我不再害怕什么', type: 'Guest', playCount: 11.2, commentCount: 426 },
  { id: 'E18', title: '投资就是你的样子', type: 'Guest', playCount: 8.1, commentCount: 230 },
  { id: 'E19', title: '无尽的探索', type: 'Solo', playCount: 20.3, commentCount: 811 },
  { id: 'E20', title: '未解之谜', type: 'Solo', playCount: 9.1, commentCount: 241 },
  { id: 'E21', title: '标好了价格', type: 'Solo', playCount: 35.3, commentCount: 1066 },
  { id: 'E22', title: '成为大多数人', type: 'Guest', playCount: 17.8, commentCount: 569 },
  { id: 'E23', title: '此时此刻', type: 'Solo', playCount: 16.4, commentCount: 1212 },
  { id: 'E24', title: '真实，自有万钧之力', type: 'Guest', playCount: 20.4, commentCount: 1135 },
  { id: 'E25', title: '太阳与六便士', type: 'Guest', playCount: 13.1, commentCount: 416 },
  { id: 'E26', title: '寻找自己的游戏', type: 'Guest', playCount: 15.4, commentCount: 346 },
  { id: 'E27', title: '哦', type: 'Guest', playCount: 15.0, commentCount: 1554 },
  { id: 'E28', title: '对话 Steve', type: 'Guest', playCount: 51.7, commentCount: 1294 },
  { id: 'E30', title: '让奇迹发生', type: 'Solo', playCount: 66.9, commentCount: 2139 },
  { id: 'E31', title: '中', type: 'Solo', playCount: 15.8, commentCount: 1057 },
  { id: 'E32', title: '生命大梦一场', type: 'Guest', playCount: 43.7, commentCount: 1902 },
  { id: 'E33', title: '与自由的距离', type: 'Solo', playCount: 29.5, commentCount: 1053 },
  { id: 'E34', title: '和100岁的你', type: 'Guest', playCount: 34.8, commentCount: 1190 },
  { id: 'E35', title: '知识的缝隙', type: 'Solo', playCount: 43.4, commentCount: 1585 },
  { id: 'E36', title: '在高处做自己', type: 'Guest', playCount: 45.8, commentCount: 1381 },
  { id: 'E37', title: '鱼不存在', type: 'Solo', playCount: 165.3, commentCount: 6346 },
  { id: 'E38', title: '水很凉', type: 'Guest', playCount: 38.5, commentCount: 2102 },
  { id: 'E39', title: '创作过于重要', type: 'Guest', playCount: 32.7, commentCount: 1690 },
  { id: 'E40', title: '够与多', type: 'Solo', playCount: 57.4, commentCount: 2829 },
  { id: 'E41', title: '对话阿娇', type: 'Guest', playCount: 59.7, commentCount: 4743 },
  { id: 'E42', title: '沉默的主角', type: 'Guest', playCount: 53.9, commentCount: 2391 },
  { id: 'E43', title: '没有更好的生活', type: 'Guest', playCount: 17.1, commentCount: 1298 }
];
